version: "3.9"

services:

  db:
    image: postgres:14.1
    container_name: justita-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=justita
      - POSTGRES_USER=justita
      - POSTGRES_PASSWORD=1234@1234
    volumes:
      - postgres-data:/var/lib/postgresql/data/

#  pgadmin:
#    container_name: justita-pgadmin4
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
#    ports:
#      - "5050:80"



volumes:
    postgres-data:

