# Generated by Django 4.0.6 on 2024-03-09 06:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_lawyer', models.BooleanField(default=True)),
                ('licence_number', models.CharField(max_length=6)),
                ('introduction_code', models.CharField(max_length=64)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('is_male', models.BooleanField()),
                ('bio', models.CharField(max_length=512)),
                ('work_address', models.CharField(max_length=256)),
                ('national_code', models.CharField(max_length=20)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_card_images')),
                ('licence_type', models.CharField(max_length=100)),
                ('last_degree', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
