# Generated by Django 4.0.6 on 2024-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='bio',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='introduction_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='is_male',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='last_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='licence_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='licence_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='work_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
