# Generated by Django 4.0.6 on 2024-03-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lawyer_licence_image_lawyer_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='introduction_code',
            field=models.CharField(blank=True, default='XrbkL6', max_length=64, null=True),
        ),
    ]
