# Generated by Django 4.0.6 on 2024-03-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_lawyer_gender_alter_lawyer_introduction_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lawyer',
        ),
    ]
