# Generated by Django 4.0.6 on 2024-03-10 09:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_delete_lawyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('online', models.BooleanField(default=False)),
                ('licence_number', models.CharField(blank=True, max_length=6, null=True)),
                ('introduction_code', models.CharField(default=None, max_length=64)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('licence_image', models.ImageField(blank=True, null=True, upload_to='licence_images')),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('bio', models.CharField(blank=True, max_length=512, null=True)),
                ('work_address', models.CharField(blank=True, max_length=256, null=True)),
                ('office_address', models.CharField(blank=True, max_length=256, null=True)),
                ('city_working', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('national_code', models.CharField(blank=True, max_length=20, null=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_card_images')),
                ('licence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('last_degree', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'lawyer',
                'verbose_name_plural': 'lawyers',
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_min_price', models.IntegerField()),
                ('fifteen_min_price', models.IntegerField()),
                ('thirty_min_price', models.IntegerField()),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyers.lawyer')),
            ],
        ),
    ]
