# Generated by Django 4.0.6 on 2024-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_consultation_online_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultation',
            new_name='ConsultationPrice',
        ),
    ]
