# Generated by Django 4.0.6 on 2024-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_rename_consultation_consultationprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationprice',
            name='fifteen_min_price',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='online_price',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='ten_min_price',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='thirty_min_price',
            field=models.IntegerField(blank=True, default=45),
        ),
    ]
