# Generated by Django 4.0.6 on 2024-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_alter_consultationprice_fifteen_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationprice',
            name='fifteen_min_price',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='online_price',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='ten_min_price',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='thirty_min_price',
            field=models.IntegerField(blank=True, default=45, null=True),
        ),
    ]
