# Generated by Django 4.0.6 on 2024-03-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0006_alter_consultationprice_fifteen_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationprice',
            name='lawyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lawyers.lawyer'),
        ),
    ]
