# Generated by Django 4.0.6 on 2024-03-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0007_alter_consultationprice_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='subset_lawyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyers.lawyer'),
        ),
    ]
