# Generated by Django 4.0.6 on 2024-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0008_lawyer_subset_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='subset_introduction_code',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
