# Generated by Django 4.0.6 on 2024-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_lawyer_subset_introduction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='introduction_code',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
