# Generated by Django 4.0.6 on 2024-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
