# Generated by Django 4.0.6 on 2024-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0014_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='agreement_signed',
            field=models.BooleanField(default=False),
        ),
    ]
