# Generated by Django 4.0.6 on 2024-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0015_lawyer_agreement_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='IBAN_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
