# Generated by Django 4.0.6 on 2024-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0016_lawyer_iban_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
