# Generated by Django 4.0.6 on 2024-03-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0017_lawyer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='name_in_english',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
