# Generated by Django 4.0.6 on 2024-03-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0018_lawyer_name_in_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='name_in_english',
        ),
    ]
