# Generated by Django 4.0.6 on 2024-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0019_remove_lawyer_name_in_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationprice',
            name='fifteen_min_price',
            field=models.IntegerField(blank=True, default=180000, null=True),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='online_price',
            field=models.IntegerField(blank=True, default=75000, null=True),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='ten_min_price',
            field=models.IntegerField(blank=True, default=100000, null=True),
        ),
        migrations.AlterField(
            model_name='consultationprice',
            name='thirty_min_price',
            field=models.IntegerField(blank=True, default=200000, null=True),
        ),
    ]
