# Generated by Django 4.0.6 on 2024-01-27 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCounseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, unique=True, verbose_name='شناسه')),
                ('lawyer', models.CharField(blank=True, choices=[('Mohammad_Nobari', 'محمدجواد خسرو نوبری'), ('Alireza_Atashzaran', 'علیرضا آتش زران'), ('Arghavan_Mansuri', 'ارغوان منصوری'), ('Atmish_Jahanshahi', 'آتمیش جهانشاهی'), ('Niloofar_Shahab', 'نیلوفر شهاب')], max_length=64, verbose_name='وکیل')),
                ('subject', models.CharField(blank=True, default='سایر', max_length=32, verbose_name='موضوع')),
                ('call_time', models.CharField(blank=True, choices=[('20', '20 دقیقه'), ('30', '30 دقیقه'), ('45', '45 دقیقه')], default='30', max_length=3, verbose_name='مدت زمان تماس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('Reservation_time', models.TimeField(blank=True, null=True, verbose_name='زمان رزرو شده')),
                ('Reservation_day', models.DateField(blank=True, null=True, verbose_name='روز رزرو شده')),
                ('payment_status', models.CharField(blank=True, choices=[('failed', 'ناموفق'), ('ok', 'موفق'), ('undone', 'انجام نشده')], default='undone', max_length=16, verbose_name='وضعیت پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=64, verbose_name='شناسه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره تراکنش')),
                ('amount_paid', models.CharField(blank=True, max_length=32, null=True, verbose_name='مبلغ پرداخت شده')),
                ('status', models.CharField(choices=[('done', 'انجام شده'), ('undone', 'انجام نشده')], default='undone', max_length=8, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='موکل')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, unique=True, verbose_name='شناسه')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=16, verbose_name='وضعیت')),
                ('marked', models.BooleanField(default=False, verbose_name='نشان شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='موکل')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, unique=True, verbose_name='شناسه')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=16, verbose_name='وضعیت')),
                ('marked', models.BooleanField(default=False, verbose_name='نشان شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='موکل')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCounselingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, unique=True, verbose_name='شناسه')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=16, verbose_name='وضعیت')),
                ('marked', models.BooleanField(default=False, verbose_name='نشان شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='موکل')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, unique=True, verbose_name='شناسه')),
                ('lawyer', models.CharField(blank=True, choices=[('Mohammad_Nobari', 'محمد نوبری'), ('Alireza_Atashzaran', 'علیرضا آتش زران'), ('Arghavan_Mansuri', 'ارغوان منصوری'), ('Atmish_Jahanshahi', 'آتمیش جهانشیری'), ('Niloofar_Shahab', 'نیلوفر شهاب'), ('None', 'هنوز انتخاب نشده')], default='None', max_length=64, verbose_name='وکیل')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=16, verbose_name='وضعیت')),
                ('marked', models.BooleanField(default=False, verbose_name='نشان شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='موکل')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCounseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, unique=True, verbose_name='شناسه')),
                ('lawyer', models.CharField(blank=True, choices=[('Mohammad_Nobari', 'محمدجواد خسرو نوبری'), ('Alireza_Atashzaran', 'علیرضا آتش زران'), ('Arghavan_Mansuri', 'ارغوان منصوری'), ('Atmish_Jahanshahi', 'آتمیش جهانشاهی'), ('Niloofar_Shahab', 'نیلوفر شهاب')], max_length=64, verbose_name='وکیل')),
                ('payment_status', models.CharField(blank=True, choices=[('failed', 'ناموفق'), ('ok', 'موفق'), ('undone', 'انجام نشده')], default='undone', max_length=16, verbose_name='وضعیت پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=64, verbose_name='شناسه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره تراکنش')),
                ('amount_paid', models.CharField(blank=True, max_length=32, null=True, verbose_name='مبلغ پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='موکل')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCounselingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, unique=True, verbose_name='شناسه')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=16, verbose_name='وضعیت')),
                ('marked', models.BooleanField(default=False, verbose_name='نشان شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('online_counseling', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='social.onlinecounseling', verbose_name='مشاوره آنلاین')),
            ],
        ),
        migrations.CreateModel(
            name='SupportRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(blank=True, null=True, unique=True, verbose_name='شناسه')),
                ('subject', models.CharField(max_length=64, verbose_name='موضوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='SupportRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('file', models.FileField(blank=True, upload_to='assets/uploaded/support-room/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.supportroom', verbose_name='گفت گو')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCounselingRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('file', models.FileField(blank=True, upload_to='assets/uploaded/online-counseling/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.onlinecounselingroom', verbose_name='گفت گو')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPanelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('file', models.FileField(blank=True, upload_to='assets/uploaded/legal-panel/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.legalpanel', verbose_name='گفت گو')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCounselingRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.freecounselingroom', verbose_name='گفت گو')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('file', models.FileField(blank=True, upload_to='assets/uploaded/contract/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.contractroom', verbose_name='گفت گو')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('file', models.FileField(blank=True, upload_to='assets/uploaded/complaint/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.complaintroom', verbose_name='گفت گو')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
        migrations.CreateModel(
            name='CallCounselingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/uploaded/call-counseling/', verbose_name='فایل')),
                ('call_counseling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='social.callcounseling', verbose_name='مشاوره تلفنی برای :')),
            ],
        ),
    ]
