# Generated by Django 4.0.6 on 2024-03-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0017_lawyer_balance'),
        ('social', '0002_callcounseling_lawyer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecounseling',
            name='lawyer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyers_online_counseling', to='lawyers.lawyer'),
        ),
        migrations.AlterField(
            model_name='callcounseling',
            name='lawyer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyers_call_counseling', to='lawyers.lawyer'),
        ),
    ]
