# Generated by Django 4.0.6 on 2024-03-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0017_lawyer_balance'),
        ('social', '0003_onlinecounseling_lawyer_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpanel',
            name='lawyer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyers_legal_panel', to='lawyers.lawyer'),
        ),
        migrations.AddField(
            model_name='onlinecounselingroom',
            name='lawyer_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyers_online_counseling_room', to='lawyers.lawyer'),
        ),
    ]
