# Generated by Django 4.0.6 on 2024-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_legalpanel_lawyer_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcounseling',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تایید وکیل'),
        ),
    ]
